### PR TITLE
update ui and reponsiveness

### PR DESCRIPTION
**Pull request by mohitsaini07**
## What does this PR do?

Fixes # (1) Card UI

Before --
Screenshot 2023-10-08 204508

After --
Screenshot 2023-10-08 231323

## Mandatory Tasks

- [x] Could you make sure you have self-reviewed the code? A decent-sized PR without self-review might be rejected.

### CODE REVIEW

**Comment by baekusboo** [comment]
Mention the issue number in description, as fixes #ISSUE_NUMBER

**Comment by baekusboo** [comment]
Hello  @mohitsaini07 , Thanks for your valuable contribution! I have noticed that your design looks great but the header looks simple. Hence, I am closing this PR right now. You are always welcomed to contribute on this project by featuring your song or by raising any other valid issues and contributing for it! 

Happy Hacking! ^^

**Comment by mohitsaini07** [comment]
Okay, thanks for the message!

**Comment by baekusboo** [comment]
If you are interested do work on issue #23

**Pull request closed without merging**
