### PR TITLE
Bug fixed/correction in aligning like button and text card

### LINKED ISSUE #101: fix: Align like button and suggested by text in the cards
**Describe the bug**
The contributor's name and the like button are not aligned properly in the same line. When the name is too long, the position of the like button is changed.

**To Reproduce**
1. Go to '[Music World Webpage](https://music-website-jade.vercel.app/)'
2. Scroll down
3. Observe the card UI

**Expected behavior**
The contributor's name and the like button should be aligned properly in the same line. For each card, fix the position of the like button at left with required margin and padding. It would be better to align the "suggested by NAME" left. Any unique idea will be appreciated to fix this issue.

**Screenshots**

image

### PR DESCRIPTION
**Pull request by SujalRaunak**
## What does this PR do?

This PR fixes the bug and solved the issues , aligning like button and text card correctly, making website look very attractive and beautiful. I hope my work is according to your request. Kindly merge my PR.

Fixes #101 

I have made changes in styles.css

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by baekusboo** [comment]
image

Hi thanks for your contribution @SujalRaunak 

Actually the alignment is not looking neat or centered, could you please look into it? Once it's fixed, I will merge your code! Happy Hacking! ^^

**Comment by baekusboo** [comment]
If you couldn't align it properly, you can try experimenting with the card layout! Maybe change the positions of like button or suggested by text to top or bottom...

**Comment by SujalRaunak** [comment]
Hello mam
Thanks for replying.
I will do some changes. Then I will inform you.

**Comment by SujalRaunak** [comment]
I have solved your issue. Is it visible through my PR. Kindly reply mam as
soon as possible.

**Comment by SujalRaunak** [comment]
Mam
Kindly check file changed section to view updated code.

**Comment by SujalRaunak** [comment]
[image: image.png]

**Comment by baekusboo** [comment]
Have you commited your code? I am unable to see the latest changes you made here...

**Comment by SujalRaunak** [comment]
Yes, I did. Kindly scroll the navbar and click on file changed section

**Comment by SujalRaunak** [comment]
[image: 07c47ef0-dd26-402f-bae9-e58fd3792c7c.png]
file changed section on right side

**Comment by baekusboo** [comment]
image

@SujalRaunak Your PR shows only these 2 commits.

**Comment by SujalRaunak** [comment]
Mam Extend the file and you will see changes i just mentioned here the
comment. You can see all changes as shown in image in previous PR -> file
changed section of navbar (see in line of conversations, commit , file
changed ).

**Pull request merged**
