### PR TITLE
Add the Feature for Like and Filter and some fixes

### LINKED ISSUE #40: No options for Like button and Their is no filter and search
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
Need to add like button
Filter and search for songs

**Describe alternatives you've considered**
No

**Additional context**
No

### PR DESCRIPTION
**Pull request by Ravikisha**
## What does this PR do?

Fixes #40 

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by baekusboo** [comment]
Great Contribution. I would request you to first raise an appropriate issue and then link that issue with this PR to be considered!

**Comment by Ravikisha** [comment]
As you say things are done. Thanks for the efforts 👍

**Comment by Ravikisha** [comment]
Anything to add? Otherwise request to merge

**Comment by baekusboo** [comment]
Thanks for contributing! I will surely merge your code with in 24 hours!

**Comment by baekusboo** [comment]
Great Work! #hacktoberfest-accepted

Happy Hacking! ^^

**Pull request merged**
