### PR TITLE
Footer enhanced #151 fixed

### LINKED ISSUE #151: feat: Footer needs improvment
The footer is not properly made and it needs major enhancements.

hactoberfest232

### PR DESCRIPTION
**Pull request by inviBeast**
Fixes #151

bottomtotop button changed: The earlier button was not visible in the footer and was looking not good, so I replaced it with a svg.

Footer properly coded 

footer

### CODE REVIEW

**Comment by inviBeast** [comment]
@baekusboo review it.

**Comment by baekusboo** [comment]
Great Work @inviBeast ! I feel there is some issue with the alignment of the content in footer and the position of the back-to-top button. Also it would be great if you could work only on the footer part in this PR for resolving this issue. You can change the back-to-top button in another PR after raising another issue, if needed.

image

image

**Comment by baekusboo** [comment]
Footer looks great! Good job!

Could you fix this arrow position too?
image

**Comment by inviBeast** [comment]
Can u tell me the width of the screen at which this error is occuring

**Comment by baekusboo** [comment]
@inviBeast Maybe you could add z-index for positioning the bottom-to-top arrow.

**Comment by inviBeast** [comment]
@baekusboo that will not look good, I have fixed it .Review it if still there is any issue.

**Comment by baekusboo** [comment]
image

The arrow is still hidden behind the cards @inviBeast .

**Comment by inviBeast** [comment]
Yeah at 1300 px it was coming I have fixed that please review it.

**Comment by baekusboo** [comment]
Looks Good! Also did you check the footer in dark mode?

image

**Comment by inviBeast** [comment]
I will fix the dark mode issue in another PR

**Comment by inviBeast** [comment]
After this gets merged, I will make another PR fixing the Dark mode issue.

**Comment by baekusboo** [comment]
Okay, since you have contributed a lot already, I will merge your code! 

Great Work! #hacktoberfest-accepted

Happy Hacking! ^^

**Comment by inviBeast** [comment]
Thanks @baekusboo, by tomorrow I will fix the footer for dark mode.

**Pull request merged**
