### PR TITLE
Fixed #111 Search icon should be inside the search field

### LINKED ISSUE #111: feat: Search icon should be inside the search field
**Describe the bug**
The search icon is outside the search bar and doesn't look good . I want to place this icon in the search field so that UI of the website looks more good.

### PR DESCRIPTION
**Pull request by Akshat162001**
## What does this PR do?

Search icon should be inside the search field
 

Fixes #111

icon_Inside

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.
- [ ] yes I have reviewed the Pull request

Also Added the Logo of music world since it was visible at that time

Symbols of musixworld

### CODE REVIEW

**Comment by Akshat162001** [comment]
Hope U will Like Addtional changes of Symbol of music world addtional...

**Comment by Akshat162001** [comment]
This website really amazing i really ...Like codebase style of making this website..

**Comment by baekusboo** [comment]
Hey @Akshat162001 , I have assigned this issue to other contributor already. Hence, I couldn't merge your code right now. I appreciate your valuable time and work in this contribution. Thank you!

Also, I liked the footer image and changes you made! It would be great if you could raise a new feature issue and a PR for the same. I will assign you the issue and merge your PR! Happy Hacking! ^^

**Comment by baekusboo** [comment]
@Akshat162001 would you like to resolve this issue #111 ? The issue is currently unassigned, so I will merge your PR once the merge conflict is resolved and the changes are made.

image
I hope you can adjust the width of the search bar properly. You can commit the change and I will merge your PR once everything is alright. Thanks!

**Pull request closed without merging**
