### PR TITLE
back to top button, toggle theme button position fix

### LINKED ISSUE #107: feat: Adding icon to get to the top of the webpage
**Is your feature request related to a problem? Please describe.**
Scrolling to the top of the website from the bottom is hard to do manually. It's hectic especially when there are more and more cards added to the webpage everyday!

**Describe the solution you'd like**
Adding some icon at the bottom of the webpage to get to top of the webpage instantly.

**Describe alternatives you've considered**
Maybe adding an arrow shaped icon would be better.

### PR DESCRIPTION
**Pull request by NisooJadhav**
Fixes #107

https://github.com/baekusboo/music-website/assets/68807845/78a5719a-6fa5-4792-b669-2b0f194578b3

### CODE REVIEW

**Comment by baekusboo** [comment]
Hey @NisooJadhav , Your contribution for the arrow is great! Just make sure you remove all the other changes you made in the repo apart from the assigned issue. No need to raise another PR, just commit again in your repo - the changes will be reflected here. I will merge your code once you remove the other changes you made in theme icon position, font, colours etc.

**Comment by NisooJadhav** [comment]
@baekusboo a PR by someone has broken your site alignment, you can see it here: https://music-website-jade.vercel.app/ 
current

why don't you just merge my PR which will make the site look like this:
https://music-website-git-fork-nisoojadhav-main-baekusboo.vercel.app/

I know you want separate features in separate issues and I will follow it in the future. I have prepared the card animations and local storage-based theme preference. I will create separate issues for them.

**Comment by baekusboo** [comment]
@NisooJadhav **Your contribution is great but there are other issues which you have solved in this PR, while others are working on it separately.** If I merge your PR which resolves multiple issues together, how will others be able to contribute? This is a beginner friendly repo and thus I made minute issues so that everyone can contribute for hacktoberfest easily! Hope you understand why I am asking you to make only the required changes in this website. 

The current webpage alignment is looking fine at my end, the cards were Centre aligned, screenshot attached below.

image

Also, If you notice the below 2 screenshots, if I merge yours... the shadow effect present in cards is not visible as you have changed the bg colour for dark theme in this PR! I appreciate that you wanted to improve the webpage look and UI, but since there are other contributors assigned to those tasks, I couldn't merge this PR right away.

image
..
image

**Comment by baekusboo** [comment]
Please rectify the merge conflict and do add only the arrow feature code in the webpage for this PR/MR so it will be easy for me to merge it right away! I really appreciate the time and efforts you have taken for this project! Happy Hacking! ^^

**Comment by NisooJadhav** [comment]
@baekusboo I completely understand, no worries.

Thank you for reaching back.

**Pull request closed without merging**
