### PR TITLE
Cards UI improved 

### LINKED ISSUE #23: Improvement in UI of song cards
I want to enhance the UI of the song cards and make them look much more vibrant and less congested.
Please assign this issue to me under hacktoberfest 2023.

### PR DESCRIPTION
**Pull request by harshverma2002**
This enhances the UI of cards on the homepage
This adds more gap between cards and improved colours to resonate with the background
This implements changes in dark mode also
This PR fixes #23 

Screenshot (116)
Screenshot (117)

### CODE REVIEW

**Comment by baekusboo** [comment]
Hello @harshverma2002 , I have noticed your changes. It's great! It would be even better if you could remove some space. I could notice a lot of white spaces. Maybe you can reduce the margin or gaps between cards (try having at least 4 cards in a row) and also the gap between the header and the cards is more. 

Also, you could try having the contributors name at the top of the card instead of having it at the bottom. 

I loved the shadow effect in cards! It would be cool if it's present in dark mode too! You could try making the cards bright in light mode so that it matches with the heading colour (Maybe you can try adding some goldish yellow or light pink shade for the contributor name bg instead of having it white...).

Once the changes are done, do comment and tag me so I will take a look! Thanks for working on this issue!

Happy Hacking! ^^

**Comment by harshverma2002** [comment]
Changes have been made @baekusboo 

Screenshot 2023-10-10 194714

Screenshot 2023-10-10 194742

**Comment by baekusboo** [comment]
image

The dark shadow for the cards are great! Could you look into this spacing between cards? I am still getting only 3 cards in a single row. The card colours are not changing when theme is changed - could you look into that?

**Comment by harshverma2002** [comment]
Since the cards have dynamic class name its not possible change their colors as for every card a new HTML document is inserted with the iframe. Check if the looks better 

save-3
Changed the bgColor of p to match the card color for linearity.

save-4

**Comment by baekusboo** [comment]
image

There is some issue with the card size. Instead of changing the card size, could you modify the gap/spacings alone?

Also let the contributor-name-font-colour be plain black or white depending on the theme, the gradient is not properly visible in light mode.

**Comment by harshverma2002** [comment]
@baekusboo check now

**Comment by baekusboo** [comment]
image

The card sizes are great! Love the view in light mode!

Changes needed: These cards are aligned to right instead of center. Also in dark mode, the contributor-name-text is not visible.

**Comment by baekusboo** [comment]
Hey @harshverma2002, kindly check PR #37 .... I would like you to add your contribution = card-shadow-effects to the cards when its hovered! Could you work on that as a new issue?

**Comment by harshverma2002** [comment]
@baekusboo Please give other contributors a chance to work on these issues. I have contributed enough and want to explore more projects. I request to merge this PR under Hacktoberfest 2023 and please create new issues so that other developers can also contribute.

**Comment by baekusboo** [comment]
Thank you so much for contributing @harshverma2002 ! I will surely merge yours within 24 hours!

**Comment by baekusboo** [comment]
Great Work! #hacktoberfest-accepted

Happy Hacking! ^^

**Pull request merged**
